name: benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: my_env
          use-mamba: true

      - uses: CodSpeedHQ/action@v3
        with:
          run: conda run -n my_env pytest tests/ --codspeed
